### ISSUE TITLE
Problem with h1 and h2, not with h3, not with h2+class

### ISSUE THREAD

**Issue by noordo** [gerardnico/dokuwiki-plugin-webcode#2]
Hello,

A picture of a problem that i have with this extension.
![bug with h2](http://marris.free.fr/img/2016-10-28_104355.jpg)

Thanks.

**Comment by gerardnico** [comment]
Sorry but without seeing the code, it will be difficult for me to see why you get it. I didn't have this problem.
http://gerardnico.com/wiki/dokuwiki/webcode_test

**Comment by gerardnico** [comment]
I just take a look and it seems that you have a script (php for me, I could'nt find a javascript one) that changes the H1 header. If you take a look closely, you will see that all your H1 have the class: "page-header" added to them. I didn't change any code in my plugin then it's very unlikely that it comes from the webcode plugin. Is it a behavior your are aware of ?

**Comment by noordo** [comment]
For the "bootstrap3" template, in the file ".../lib/tpl/bootstrap3/tpl_functions.php" :
Line 1702
`$content = preg_replace('/<h([1-2])>/',                        '<h$1 class="page-header">',            $content);`
If I replace the previous row with the one below, it seems to fix the problem.
`$content = preg_replace('/<h([1-2])>/',                        "<h$1 class='page-header'>",            $content);`
I hope there will be no induced disturbances.
Thanks.

**Comment by gerardnico** [comment]
Yeh then it's the culprit. I can't solve it. If you change your template, the problem must be solved.

**Comment by gerardnico** [comment]
You will still get the class in all H1 but it's a nice solution :)
