### ISSUE TITLE
Problem : backslashes are added.

### ISSUE THREAD

**Issue by noordo** [gerardnico/dokuwiki-plugin-webcode#3]
Hello,

Another picture to show another problem:
![Problem with backslash](http://marris.free.fr/img/2016-10-28_105833.jpg)

Thanks

**Comment by gerardnico** [comment]
Yes. I use an inline attribute (srcodc) to pass the code. You need to use a double quote. As here: http://gerardnico.com/wiki/dokuwiki/webcode#the_output

**Comment by gerardnico** [comment]
I have pushed new code today that solve this problem. The code is now written in the file in the dokuwiki cache. Therefore, this is no more needed to play with the quotes. The cache is not yet suppressed if the code change. And I just see that I could have done it easier by encoding with HTML entities but ... that's life.
