### ISSUE TITLE
jsfiddle.net/api/post/jQuery/edge/dependencies/Lite/

### ISSUE THREAD

**Issue by noordo** [gerardnico/dokuwiki-plugin-webcode#5]
`$postURL = "http://jsfiddle.net/api/post/jQuery/2.1.3/";`

Hello,
it seems as if the previous line is replaced with the following line, it is possible to display "console.log" in Firebug Lite console on jsFiddle. Is it possibly to detect if "console.log" is used in the script and then fit the link to jsFiddle to also have the console?

`$postURL = "https://jsfiddle.net/api/post/jQuery/edge/dependencies/Lite/";`

Thanks.

**Comment by noordo** [comment]
But perhaps that Firebug-Lite is too slow to display.
To offer this possibility as an option ?

**Comment by gerardnico** [comment]
Where did you get this information ? Edge is the last **not** stable built of JQuery. Then I'm not really hot to do so. Does it work with a stable version ?
